apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: jerinpaul/java-app:latest
          ports:
            - containerPort: 8080  # Update this to the port your application listens on
